# Generated by Django 3.2.10 on 2022-01-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.SmallIntegerField(choices=[(0, 'Not published'), (1, 'Published')]),
        ),
    ]
