# Generated by Django 3.2.10 on 2022-01-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220115_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default='Bio about blogger.'),
        ),
    ]
