# Generated by Django 3.2.10 on 2022-01-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogger_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')]),
        ),
    ]
