# Generated by Django 3.2.10 on 2022-01-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
